### ISSUE TITLE
Scroll and sorting issue

### ISSUE THREAD

**Issue by godaji** [anhdocntt/sky-chat#6]
I think scroll and chat text has some problem.

Whenever I write new text, It looks like get all data and sort it.

Can you improve it?

**Comment by godaji** [comment]
Hint

You use 'useFirestore' in ChatWindowContent(). You useless change data and re-render it. I believe you can improve it.

**Comment by anhdocntt** [comment]
Hi,
Thank you for this issue. I tried to improve it by only updating new data without retrieving all the data from the database. You can see my commit at: https://github.com/anhdocntt/sky-chat/commit/5d7401b4c0bc610b3f0907099f4ca5755ccd8ef3

**Comment by godaji** [comment]
Thank you for your commit! It works well :)
