### ISSUE TITLE
Can you record your English voice?

### ISSUE THREAD

**Issue by godaji** [anhdocntt/sky-chat#8]
As I mentioned in email, I want to listen your Englishg accent, before interview.

Can you do it for me? You can record your voice below, 

https://ttalk.onrender.com

**Comment by anhdocntt** [comment]
Hi, it's not convenient for me to voice right now but I will complete it for you as soon as possible. I want to ask you if I will voice all the topics, right?

**Comment by godaji** [comment]
Sorry for your inconvenient. Few topic is ok (2~3 topic) it will take 5 minutes.

We request this because many applicants have good programming skills but have difficulty communicating in English.

Thank you for your understanding.

By the way, my techtalk nickname is 'shhong' You can listen my voice also :)

**Comment by anhdocntt** [comment]
Hi, I recorded my English voice, my nickname is "Anh Do". Thank you very much.

**Comment by godaji** [comment]
Thank you for your work. I listened it and let's do interview! 
My co-worker will let you know it via e-mail tomorrow!
